### ISSUE TITLE
Инфраструктура и гайды по управлению сертификатами

### ISSUE THREAD

**Issue by n013e** [f-me/system#12]
По моим представлениям у нас сертификаты используются в следующих местах:
- мобильное приложение для iPhone
- клиентское мобильное приложение для Android
- партнёрское мобильное приложение для Android
- партнёрские клиентские мобильные приложения для Android

Ещё у нас есть сертификат на https://*.ruamc.ru
У ничего не упустил? Вопрос прежде всего к @dzhus 
Нужно понять когда это всё хозяйство делает expire (@dzhus) и придумать как их обновлять (@varuzam при всеобщей поддержке). Нужна какая-то краткая дока и набор нотификаций (в календаре, например), чтобы не просыпать моменты, когда нам нужно что-то сделать.

**Comment by dzhus** [comment]
Тогда надо делать автообновление.

**Comment by dzhus** [comment]
https://docs.google.com/document/d/1PkbAMJ5zQ5odTkhuXfPO-QzZa72a09QNixD3ilKSBgs/edit
